import type {Product} from '@/domain/product';

const now = Date.now();
const daysAgo = (days: number) => new Date(now - days * 86_400_000).toISOString();

export const FURNITURE_CATEGORIES = ['Sofa', 'Chair', 'Table', 'Bed', 'Storage', 'Home Decor'] as const;

export const FURNITURE_PRODUCTS: Product[] = [
  {
    id: 'furniture-1',
    itemCode: 'RF-001',
    name: 'Sage Lounge Chair',
    category: 'Chair',
    color: 'Sage Green',
    size: '82 × 78 × 84 cm',
    price: 680000,
    promoPrice: null,
    isPromotion: false,
    stock: 8,
    inStock: true,
    status: 'active',
    images: [
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=88',
      'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?auto=format&fit=crop&w=1200&q=88',
    ],
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=88',
    description: 'နူးညံ့တဲ့ Sage Green အထည်သားနဲ့ ထိုင်ခုံကျယ်ကျယ်၊ သစ်သားခြေထောက်ခိုင်ခိုင်ပါရှိတဲ့ Lounge Chair ဖြစ်ပါတယ်။ စာဖတ်ခန်းထောင့်၊ ဧည့်ခန်းနဲ့ Modern Interior တွေအတွက် သင့်တော်ပြီး အိမ်အတွင်းကို တည်ငြိမ်နွေးထွေးတဲ့အမြင်ပေးပါတယ်။',
    arrivalDate: daysAgo(2),
    createdAt: daysAgo(2),
  },
  {
    id: 'furniture-2',
    itemCode: 'RF-002',
    name: 'Blush Accent Chair',
    category: 'Chair',
    color: 'Dusty Pink',
    size: '78 × 74 × 80 cm',
    price: 720000,
    promoPrice: 650000,
    isPromotion: true,
    stock: 6,
    inStock: true,
    status: 'active',
    images: [
      'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?auto=format&fit=crop&w=1200&q=88',
      'https://images.unsplash.com/photo-1598300056393-4aac492f4344?auto=format&fit=crop&w=1200&q=88',
    ],
    image: 'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?auto=format&fit=crop&w=1200&q=88',
    description: 'နူးညံ့တဲ့ Blush Pink အထည်သားနဲ့ ဝိုင်းဝိုင်းလေးဒီဇိုင်းလုပ်ထားတဲ့ Accent Chair ဖြစ်ပါတယ်။ နေရာမစားဘဲ အခန်းထဲမှာ အရောင်အသွေးနဲ့ Premium 느낌 ပေးနိုင်တဲ့ Statement Piece တစ်ခုပါ။',
    arrivalDate: daysAgo(5),
    createdAt: daysAgo(5),
  },
  {
    id: 'furniture-3',
    itemCode: 'RF-003',
    name: 'Nova 3-Seater Sofa',
    category: 'Sofa',
    color: 'Warm Ivory',
    size: '210 × 88 × 82 cm',
    price: 1290000,
    promoPrice: 1180000,
    isPromotion: true,
    stock: 4,
    inStock: true,
    status: 'active',
    images: [
      'https://images.unsplash.com/photo-1540574163026-643ea20ade25?auto=format&fit=crop&w=1400&q=88',
      'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&w=1400&q=88',
    ],
    image: 'https://images.unsplash.com/photo-1540574163026-643ea20ade25?auto=format&fit=crop&w=1400&q=88',
    description: 'ထိုင်ခုံ ၃ယောက်စာ ကျယ်ဝန်းပြီး နူးညံ့တဲ့ Neutral Fabric၊ အားကောင်းတဲ့ Cushion နဲ့ သစ်သားအောက်ခံပါရှိတဲ့ Sofa ဖြစ်ပါတယ်။ Yangon Apartment နဲ့ Family Living Room တွေအတွက် အရွယ်အစားသင့်တော်ပြီး Modern Look ရရှိစေပါတယ်။',
    arrivalDate: daysAgo(8),
    createdAt: daysAgo(8),
  },
  {
    id: 'furniture-4',
    itemCode: 'RF-004',
    name: 'Oak Round Dining Table',
    category: 'Table',
    color: 'Natural Oak',
    size: '120 cm diameter',
    price: 950000,
    promoPrice: null,
    isPromotion: false,
    stock: 5,
    inStock: true,
    status: 'active',
    images: [
      'https://images.unsplash.com/photo-1533090481720-856c6e3c1fdc?auto=format&fit=crop&w=1400&q=88',
      'https://images.unsplash.com/photo-1617806118233-18e1de247200?auto=format&fit=crop&w=1400&q=88',
    ],
    image: 'https://images.unsplash.com/photo-1533090481720-856c6e3c1fdc?auto=format&fit=crop&w=1400&q=88',
    description: 'Natural Oak သစ်သားနဲ့ပြုလုပ်ထားတဲ့ ဝိုင်းပုံ Dining Table ဖြစ်ပြီး Sculptural Pedestal Base ပါရှိပါတယ်။ လူ ၄ယောက်အထိ အဆင်ပြေပြေထိုင်နိုင်ပြီး Dining Area အသေးတွေမှာတောင် နေရာချရလွယ်ကူပါတယ်။',
    arrivalDate: daysAgo(12),
    createdAt: daysAgo(12),
  },
  {
    id: 'furniture-5',
    itemCode: 'RF-005',
    name: 'Cloud Platform Bed',
    category: 'Bed',
    color: 'Oak / Linen',
    size: 'Queen',
    price: 890000,
    promoPrice: null,
    isPromotion: false,
    stock: 3,
    inStock: true,
    status: 'active',
    images: [
      'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1400&q=88',
      'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1400&q=88',
    ],
    image: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1400&q=88',
    description: 'Low-profile Queen Bed ဒီဇိုင်းဖြစ်ပြီး နွေးထွေးတဲ့ သစ်သား Frame နဲ့ Upholstered Headboard ပါရှိပါတယ်။ အိပ်ခန်းအသေးတွေကိုတောင် ပိုကျယ်ပြီး သန့်ရှင်းတည်ငြိမ်သလို မြင်ရစေပါတယ်။',
    arrivalDate: daysAgo(14),
    createdAt: daysAgo(14),
  },
  {
    id: 'furniture-6',
    itemCode: 'RF-006',
    name: 'Rattan Sideboard',
    category: 'Storage',
    color: 'Walnut',
    size: '160 × 42 × 78 cm',
    price: 580000,
    promoPrice: 525000,
    isPromotion: true,
    stock: 7,
    inStock: true,
    status: 'active',
    images: [
      'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1400&q=88',
      'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=1400&q=88',
    ],
    image: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1400&q=88',
    description: 'နွေးထွေးတဲ့ သစ်သားအရောင်နဲ့ Textured Front Panel ပါရှိတဲ့ Sideboard ဖြစ်ပါတယ်။ အတွင်းသိုလှောင်ခန်းကျယ်ပြီး Dining Cabinet၊ TV Console သို့မဟုတ် Entry Storage အဖြစ် အသုံးပြုနိုင်ပါတယ်။',
    arrivalDate: daysAgo(17),
    createdAt: daysAgo(17),
  },
  {
    id: 'furniture-7',
    itemCode: 'RF-007',
    name: 'Mira Side Table',
    category: 'Table',
    color: 'Natural Oak',
    size: '48 × 48 × 52 cm',
    price: 280000,
    promoPrice: null,
    isPromotion: false,
    stock: 11,
    inStock: true,
    status: 'active',
    images: [
      'https://images.unsplash.com/photo-1532372320572-cda25653a694?auto=format&fit=crop&w=1200&q=88',
    ],
    image: 'https://images.unsplash.com/photo-1532372320572-cda25653a694?auto=format&fit=crop&w=1200&q=88',
    description: 'ကျစ်လစ်သေးငယ်တဲ့ ဝိုင်းပုံ Side Table ဖြစ်ပြီး ရိုးရှင်းတဲ့ သစ်သားဒီဇိုင်းနဲ့ ဖန်တီးထားပါတယ်။ Lounge Chair၊ Sofa သို့မဟုတ် Bed ဘေးမှာ နေရာမစားဘဲ အလွယ်တကူအသုံးပြုနိုင်ပါတယ်။',
    arrivalDate: daysAgo(21),
    createdAt: daysAgo(21),
  },
  {
    id: 'furniture-8',
    itemCode: 'RF-008',
    name: 'Linen Floor Lamp',
    category: 'Home Decor',
    color: 'Black / Linen',
    size: '165 cm height',
    price: 240000,
    promoPrice: null,
    isPromotion: false,
    stock: 9,
    inStock: true,
    status: 'active',
    images: [
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1200&q=88',
    ],
    image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1200&q=88',
    description: 'Slim Design နဲ့ Linen Shade ပါရှိတဲ့ Floor Lamp ဖြစ်ပြီး နွေးထွေးနူးညံ့တဲ့ Ambient Light ပေးစွမ်းပါတယ်။ ဧည့်ခန်းနဲ့ စာဖတ်ခန်းထောင့်တွေကို ပိုပြည့်စုံသပ်ရပ်စေတဲ့ Decor Piece တစ်ခုပါ။',
    arrivalDate: daysAgo(24),
    createdAt: daysAgo(24),
  },
  {
    id: 'furniture-9',
    itemCode: 'RF-009',
    name: 'Studio Work Desk',
    category: 'Table',
    color: 'Oak / Black',
    size: '120 × 60 × 75 cm',
    price: 420000,
    promoPrice: 390000,
    isPromotion: true,
    stock: 10,
    inStock: true,
    status: 'active',
    images: [
      'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=1400&q=88',
    ],
    image: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=1400&q=88',
    description: 'နွေးထွေးတဲ့ သစ်သား Table Top နဲ့ Clean Dark Frame ပေါင်းစပ်ထားတဲ့ Minimal Work Desk ဖြစ်ပါတယ်။ Laptop Work အတွက်အဆင်ပြေပြီး အခန်းထဲမှာ နေရာမပြည့်ကျပ်သလို သန့်ရှင်းတဲ့အမြင်ရစေပါတယ်။',
    arrivalDate: daysAgo(28),
    createdAt: daysAgo(28),
  },
  {
    id: 'furniture-10',
    itemCode: 'RF-010',
    name: 'Arc Lounge Sofa',
    category: 'Sofa',
    color: 'Moss Green',
    size: '185 × 86 × 78 cm',
    price: 980000,
    promoPrice: null,
    isPromotion: false,
    stock: 2,
    inStock: true,
    status: 'active',
    images: [
      'https://images.unsplash.com/photo-1550226891-ef816aed4a98?auto=format&fit=crop&w=1400&q=88',
    ],
    image: 'https://images.unsplash.com/photo-1550226891-ef816aed4a98?auto=format&fit=crop&w=1400&q=88',
    description: 'လူ ၂ယောက်စာ Compact Lounge Sofa ဖြစ်ပြီး ဝိုင်းဝိုင်း Armrest နဲ့ နိမ့်နိမ့် Grounded Profile ပါရှိပါတယ်။ Moss Green အရောင်က Natural Material တွေနဲ့ လွယ်ကူစွာတွဲဖက်နိုင်ပြီး အခန်းထဲမှာ Contrast ကောင်းကောင်းပေးနိုင်ပါတယ်။',
    arrivalDate: daysAgo(31),
    createdAt: daysAgo(31),
  },
];

export const FURNITURE_FEATURED_IDS = ['furniture-1', 'furniture-2', 'furniture-3', 'furniture-4', 'furniture-5', 'furniture-6'];

export const FURNITURE_BEST_SELLING_IDS = ['furniture-3', 'furniture-1', 'furniture-6', 'furniture-4', 'furniture-10', 'furniture-2'];

export function furnitureProduct(id: string | undefined): Product | null {
  if (!id) return null;
  return FURNITURE_PRODUCTS.find((product) => product.id === id) ?? null;
}
